### ISSUE TITLE
Diagnostic if the animation cannot be found

### ISSUE THREAD

**Issue by sonnyp** [JCWasmx86/GTKCssLanguageServer#1]
Just something I noticed that we could do is showing a diagnostic if the `animation-name` does not exist.

```css
#logo {
  animation-name: foo; /* should be breathing */
  animation-duration: 3s;
  animation-timing-function: ease-out;
  animation-iteration-count: infinite;
  animation-direction: normal;
  animation-delay: 0s;
  animation-fill-mode: none;
  animation-play-state: running;
}

@keyframes breathing {
  0% {
    -gtk-icon-transform: scale(0.9);
  }

  25% {
    -gtk-icon-transform: scale(1);
  }

  60% {
    -gtk-icon-transform: scale(0.9);
  }

  100% {
    -gtk-icon-transform: scale(0.9);
  }
}
```
